export const MENU = [
  { to: '/facilities', label: 'Facilities', permission: 'facility.view' },
  { to: '/users', label: 'Users', permission: 'user.view' },
  { to: '/roles', label: 'Roles', permission: 'role.view' },
  { to: '/audit-log', label: 'Audit Log', permission: 'audit.view' },

  // phase 2
  // { to: '/roles', label: 'Roles', permission: 'role.view' },
  { to: '/departments', label: 'Departments', permission: 'department.view' },
  { to: '/locations', label: 'Locations', permission: 'location.view' },
  { to: '/equipment-categories', label: 'Equipment Categories', permission: 'equipment_category.view' },
  { to: '/vendors', label: 'Vendors', permission: 'vendor.view' },
  { to: '/funding-sources', label: 'Funding Sources', permission: 'funding_source.view' },
  { to: '/equipment-models', label: 'Equipment Models', permission: 'equipment_model.view' },
  { to: '/documents', label: 'Documents', permission: 'document.view' },
  { to: '/equipment', label: 'Equipment', permission: 'equipment.view' },
  { to: '/work-orders', label: 'Work Orders', permission: 'work_order.view' },
  { to: '/pm-due', label: 'PM Due', permission: 'maintenance_plan.view' },
  { to: '/maintenance-plans', label: 'Maintenance Plans', permission: 'maintenance_plan.view' },
  { to: '/checklist-templates', label: 'Checklist Templates', permission: 'checklist_template.view' },
  { to: '/spare-parts', label: 'Spare Parts', permission: 'spare_part.view' },
  { to: '/calibration', label: 'Calibration', permission: 'calibration.view' },
  { to: '/warranties', label: 'Warranties', permission: 'warranty.view' },
  { to: '/amc-contracts', label: 'AMC Contracts', permission: 'amc.view' },
  { to: '/licences', label: 'Licences', permission: 'licence.view' },
  { to: '/compliance', label: 'Due & Expiry', permission: 'calibration.view' },
]